//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.14

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "car_log")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i64,
    pub car_arrived: DateTimeWithTimeZone,
    pub car_left: Option<DateTimeWithTimeZone>,
    pub spot_id: i16,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
